### ISSUE TITLE
Add shorthand syntax for creating workflow tasks in API

### ISSUE THREAD

**Issue by davidmezzetti** [neuml/txtai#211]
Currently, the workflow tasks section requires a dictionary for each task. It is often the case that this is a single dictionary with a key of 'action' with a value containing the workflow action string as follows:

```yaml
workflow:
   index:
      tasks:
        - action: action1
        - action: action2
```

This change will add logic to check for tasks that are only strings and map them to dictionaries. In other words:

```yaml
workflow:
   index:
      tasks:
        - action1
        - action2
```

will be equal to the YAML at the top.
