### ISSUE TITLE
POST Error indexing images via Embeddings API service

### ISSUE THREAD

**Issue by edanweis** [neuml/txtai#331]
I'm getting the following error, when indexing images using POST to the txtai service url `http://txtai.default.127.0.0.1.sslip.io/add`.

`"detail":[{"loc":["body"],"msg":"value is not a valid list","type":"type_error.list"}]}`

Possible related to the FastAPI endpoint?

The same cluster is successful with text documents, but unsure how to index images. 

Is it possible to periodically index images in a remote s3 directory via a workflow?

My current workflow YAML is:

```yaml
writable: true
path: /tmp/index.tar.gz
cloud:
  provider: s3
  container: index
  key: "<key>"
  secret: "<secret>"
  host: txtai.s3.amazonaws.com
  port: 80

embeddings:
  path: "sentence-transformers/clip-ViT-B-32-multilingual-v1"
  content: true
```

I'm hoping to implement the Images embedding search in a workflow configuration, as in the [examples/images.ipynb notebook](https://github.com/neuml/txtai/blob/8a9e5592291ebce120c010bd625af3c542545cf5/examples/images.py)

**Comment by davidmezzetti** [comment]
Definitely an interesting use case here! The main issue you're running into is the underlying embedding index is expecting an image object and there is no way to do that with an the /add endpoint.

The following workflow indexes a _publicly_ accessible S3 bucket.

```yaml
workflow:
  index:
    - task: storage
    - task: retrieve
    - task: image
    - index
```

The workflow is executed like this:

```
POST workflow
{"name": "index", "elements": ["s3://path/to/bucket"]}
```

Unfortunately, the storage task does not currently support reading authentication parameters. So this method won't work with private S3 storage, which is the more likely use case here. Issue #332 has been created to address this. 

In the meantime, is there a way to attach local file storage with the images? If so, the workflow can be simplified to:

```yaml
workflow:
  index:
    - task: storage
    - task: image
    - index
```

```
POST workflow
{"name": "index", "elements": ["local:///path/to/images"]}
```

Otherwise, you can create a custom action. An example of this is here: https://colab.research.google.com/github/neuml/txtai/blob/master/examples/28_Push_notifications_with_workflows.ipynb and a snippet with pseudo code is below. 

```python
class CloudBucket:
    def __init__(self, provider, host, port, key...):
      # Store auth parameters

    def __call__(self, elements):
       # Each element is a S3 bucket to list
       for element in elements:
           # List S3 bucket
           # Get S3 URL
           # Download image from S3 locally
```

The workflow in this case looks like this:

```yaml
package.CloudBucket:
  provider: s3
  host: txtai.s3.amazonaws.com
  port: 80

workflow:
  index:
    - action: package.CloudBucket
    - task: image
    - index
```

I recommend getting the workflow working locally as a local application first then push that workflow to an API service. For example, an application can be created as follows:

```python
from txtai.app import Application

app = Application("workflow.yaml")
app.workflow("index", "s3 path, s3 bucket or local path")

app.search("search query")
```

The calls are all similar to what is found in the FastAPI version but this just allows you to rapidly test the workflow locally.

**Comment by edanweis** [comment]
That's really helpful thanks. I couldn't get the workflow working locally, using your code above, and `app.embeddings.count()` shows `0`.

```Python
from txtai.app import Application
from txtai.embeddings import Embeddings

workflow = """
writable: true
embeddings:
  path: sentence-transformers/clip-ViT-B-32-multilingual-v1
  content: true

workflow:
  index:
    tasks:
    - task: storage
    - task: image
    - action: index
"""

app = Application(workflow)

app.workflow("index", "local:///home/ubuntu/app")

s = app.search("beach")
print(s)
print(app.embeddings.count())

```

**Comment by davidmezzetti** [comment]
Glad to hear you're making progress.

Workflows return generators when run in Python. Try consuming the output. I'll update the documentation on this as it is unclear.

```python
list(app.workflow("index", "local:///home/ubuntu/app"))
```

**Comment by edanweis** [comment]
When I do that, the data is handled like an iterable collection of documents and I get 

`['l', 'o', 'c', 'a', 'l', ':', '/', '/', '/', 'h', 'o', 'm', 'e', '/', 'u', 'b', 'u', 'n', 't', 'u', '/', 'a', 'p', 'p']`

When I put the path in a list: `list(app.workflow("index",["local:///home/ubuntu/app"]))`

It returns an error:

```
File "/home/ubuntu/.local/lib/python3.10/site-packages/txtai/vectors/base.py", line 79, in index
    for document in documents:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/txtai/embeddings/transform.py", line 97, in stream
    if isinstance(document[1], dict):
TypeError: 'JpegImageFile' object is not subscriptable
```

**Comment by davidmezzetti** [comment]
Unfortunately, I found another issue with this approach that was fixed with #335. If you're willing to [install from source](https://neuml.github.io/txtai/install/#install-from-source), things will work. Below is a copy of the workflow I used.

```yaml
writable: true
embeddings:
  method: sentence-transformers
  path: sentence-transformers/clip-ViT-B-32
  content: true

workflow:
  index:
    tasks:
    - task: storage
    - task: image
    - action: index
```

Note that the clip multilingual model only supports encoding text, hence using the image encoder model in this workflow. If multilingual support is important, you can have another YAML file that is only for search.

I also updated the docs to clarify workflows run via generators (#336)

**Comment by davidmezzetti** [comment]
How are you running your k8s cluster? Are you running a local instance like the article or on cloud hosting?

**Comment by edanweis** [comment]
I'm running a local instance like the article..

**Comment by edanweis** [comment]
@davidmezzetti I'm also getting an error which seems like a yaml syntax issue?

```
miniconda3/envs/txtai/lib/python3.10/site-packages/txtai/app/base.py", line 128, in flows
    config["tasks"] = [self.resolve(task) for task in config["tasks"]]
TypeError: list indices must be integers or slices, not str
```

**Comment by davidmezzetti** [comment]
Sorry for the delay. I don't have a good idea on why it's not working with a serverless setup. I'll try to run the image workflow with a local k8s instance to see what is happening.

**Comment by edanweis** [comment]
@davidmezzetti how did the local k8s instance go?

**Comment by davidmezzetti** [comment]
@edanweis I thought I saw a comment on this thread as I received a notification email. This is still on my radar but I've been tied up on other things related to the recent txtai 5.x release.

**Comment by davidmezzetti** [comment]
@edanweis Can you share the full workflow you're using on this? The only way I'm able to reproduce this error is with invalid YAML in the workflow.

**Comment by edanweis** [comment]
Sure here it is. I have since decided to use https://github.com/rom1504/clip-retrieval which is specifically for image retrieval with the same clip model. 

```
from txtai.app import Application

workflow = """
writable: true
path: index.tar.gz
cloud:
  provider: s3
  container: index
  key: ****
  secret: ****
  host: ****
  
embeddings:
  method: sentence-transformers
  path: sentence-transformers/clip-ViT-B-32
  content: true

workflow:
  index:
    tasks:
    - task: storage
    - task: image
    - action: index
"""

app = Application(workflow)
```
