### ISSUE TITLE
What are the API endpoints to use semantic graph ?

### ISSUE THREAD

**Issue by akset2X** [neuml/txtai#394]
Glad to know that txtAI brought Semantic graph as it's new feature. By the way how to actually use it if we have other language programmes and we expect it as an API ?. 

Are there any API endpoints out like search and extract? Anybody using it ? Please let me know. It will be better(atleast for me) if we get the details on how to write the Python script into a yaml config file to use graphs, categories and topic modeling.

**Following is my config file content to start the server using uvicorn..**
```
# Index file path
path: ./tmp/index

# Allow indexing of documents
writable: True

# Enbeddings index
embeddings:
  path: sentence-transformers/all-MiniLM-L6-v2
  content: true
# I manually added these below lines upto extractor part
  functions:
  - name: graph
    function: graph.attribute
  expressions:
  - name: category
    expression: graph(indexid, 'category')
  - name: topic
    expression: graph(indexid, 'topic')
  - name: topicrank
    expression: graph(indexid, 'topicrank')
  graph:
    limit: 15
    minscore: 0.1
    topics:
      categories:
      - Society & Culture
      - Science & Mathematics
      - Health
      - Education & Reference
      - Computers & Internet
      - Sports
      - Business & Finance
      - Entertainment & Music
      - Family & Relationships
      - Politics & Government

extractor:
  path: distilbert-base-cased-distilled-squad

textractor:
    paragraphs: true
    minlength: 100
    join: false
```
**Output:** 
```
...
ModuleNotFoundError: No module named 'graph' 
ERROR: Application startup failed. Exiting
```
