### ISSUE TITLE
Two models for embedding in parallel

### ISSUE THREAD

**Issue by akset2X** [neuml/txtai#524]
I am using txtAI functionality through REST API. Currently, I'm using all-MiniLM-L6-v2 but can I have another model for embedding at the same time ?

At the upsert/index time and search time, I should have the option to choose which model to use. That I will be choosing based on the language of the text. How can I achieve this?

**Comment by davidmezzetti** [comment]
With 6.0, you can now have multiple indexes. See the example below for applications.

```python
# Create embeddings with subindexes
embeddings = Embeddings(
  content=True,
  defaults=False,
  indexes={
    "index1": {
      "path": "sentence-transformers/all-MiniLM-L6-v2"
    },
    "index2": {
      "path": "sentence-transformers/nli-mpnet-base-v2"
    }
  }
)
embeddings.index(data)

# Query index1
embeddings.search("select id, text, score from txtai where similar('query', 'index1')")

# Query index2
embeddings.search("select id, text, score from txtai where similar('query', 'index2')")
```

The same can be done through an application/API. The config would be.

```yaml
embeddings:
  content: True
  defaults: False
  indexes: 
    index1:
      path: "sentence-transformers/all-MiniLM-L6-v2"
    index2:
      path: "sentence-transformers/nli-mpnet-base-v2"
```

Now this builds two separate indexes both with all the data. If you're looking to have index1 and index2 have a subset of the data, I'd create two separate fields in your JSON. For example:

```python
document = {"text1: "text1", "text2", "text2"}
```

And config to set the index fields.

```yaml
embeddings:
  content: True
  defaults: False
  indexes: 
    index1:
      path: "sentence-transformers/all-MiniLM-L6-v2"
      columns:
        text: text1
    index2:
      path: "sentence-transformers/nli-mpnet-base-v2"
      columns:
        text: text2
```

You can read more on this in this article: https://medium.com/neuml/whats-new-in-txtai-6-0-7d93eeedf804
