### ISSUE TITLE
Is it possible to add chat history to extractor workflow?

### ISSUE THREAD

**Issue by vnguye65** [neuml/txtai#575]
I have the following config.yml. Is it possible to add chat history to the template? 
```
writable: true
path: index

embeddings:
  path: sentence-transformers/multi-qa-mpnet-base-dot-v1
  content: true

extractor:
  path: google/flan-t5-base
  context: 3
  output: flatten

workflow:       
  search:
    tasks:
      - task: extractor
        template: |          
          Chat history: 
          {history}
          Answer the following question using only the context below and the above chat history. Say "I don't have data on that" when the question can't be answered.
          Question: 
          {text}
          Context: 
        
        action: extractor

```
