### ISSUE TITLE
Change format of the prompt in Extractor? 

### ISSUE THREAD

**Issue by vnguye65** [neuml/txtai#579]
Is it possible to change the format of the prompt to have the context before the question in the `Extractor` class for a text generation model?

**Comment by vnguye65** [comment]
Thank you for your help. Could you provide an example of how this can be done using workflow? I'm having trouble passing results from `Embeddings` to the `Template` task for LLM.

**Comment by vnguye65** [comment]
@davidmezzetti I checked the documentation and currently it doesn't look like there is a way to pass results from previous action to the next action while taking in additional inputs in the config.yml.
Could you please take a look? 
Any help is appreciated. 
```
writable: true
LLM:
   path: google/flan-t5-large
  
embeddings:
  path: sentence-transformers/multi-qa-mpnet-base-dot-v1
  content: true
  

workflow:       
  search:
    tasks:
      - action: search
      - task: template
        template: |-
          {Context}
          {Question}
        action: LLM
```
