### ISSUE TITLE
Vector Embedding Database not persisting when using YAML configuration

### ISSUE THREAD

**Issue by vnguye65** [neuml/txtai#600]
I have the following workflow configuration with subindices for two different datasets. 

workflow.yaml
```
writable: true
path: vector-database

embeddings:
  content: true
  defaults: false
  indexes: 
      document:
          path: sentence-transformers/multi-qa-mpnet-base-dot-v1
          tokenize: true
          columns:
              text: document
      csv: 
           path: sentence-transformers/multi-qa-mpnet-base-dot-v1
           tokenize: true
           columns:
               text: csv
```

After adding the data, `app.count()` returns 1. However, when this data doesn't persist when the session is refreshed. `app.count()` returns 0 when run in another separate environment. 
```
from txtai.app import Application

app = Application("search-workflow.yaml")
app.add([{'document': 'dummy data 1',
            'csv': 'dummy data 2'}])
app.upsert()
app.count()
```

@davidmezzetti Could you please confirm if I am missing anything in the code and suggest what we could do to persist data?
