### ISSUE TITLE
txtai Production Deployment 

### ISSUE THREAD

**Issue by jbouder** [neuml/txtai#608]
I’m trying to understand what a production deployment should look like when using txtai for embeddings and LLM integration.

We are currently running an app which utilizes a containerized deployment of txtai to Azure Kubernetes Service, using GPU supported nodes. The txtai app makes use of a workflow for performing the search and calling an LLM to improve the response. We also are using subindexes to support filtering of data. And we are using content storage.

With a default pod deployment when the pod is restarted, the embedding data is lost (as expected), so we’re trying to overcome that and provide a more available solution. Based on my research and testing, I believe the following to be true, through existing txtai configurations:

- embedding and index data is stored locally on disk
- content is stored in a local database (MySql)
- In order to persist data, we need to externalize both the local storage and the database
- We can persist local data using standard container/kubernetes mounting
- We can persist content data using an external database like Postgres 

We have been able to get this working with a more standard deployment, but not with our current design. We can add and index successfully, but receive an error when calling our search workflow. 

Assuming the above is accurate, I’m wondering if there may be some issue with using subindexes, as we are not seeing data in the text column in the sessions table with this setup.

Any information you can provide would be greatly appreciated!!

**Comment by jbouder** [comment]
Yup, i've seen those both, but might take a second look at the first article again.

One quick question, before digging deeper...is the SQLite database stored locally as well? And if so, where is that stored on disk? I assume there would be a .sqlite file somewhere. I'm wondering if I might be able to just make sure that this file is also mapped to an external storage mount, instead of using an full external database like postgres.

Ok, now to dig further. Do you have any idea if this setup should work with subindexes? Thats one of the main differences we have between our working and non-working instances. The reason i'm focusing on that is because our non-working instance database appears to be some missing data in the sections table. See below:

### Working instance with just 1 index:
<img width="932" alt="Screenshot 2023-12-03 at 7 46 23 PM" src="https://github.com/neuml/txtai/assets/61591423/9d820416-a248-4903-83c2-e2133a3fea02">

### Not working, with subindexes:
<img width="733" alt="Screenshot 2023-12-03 at 7 46 35 PM" src="https://github.com/neuml/txtai/assets/61591423/c4e6b513-84fe-41d9-8f95-225e2fdb604f">

And here is the main section of our config.yml:
```
writable: true
path: /mnt/data

embeddings:
  content: client
  defaults: false
  indexes:
    ds1:
      path: sentence-transformers/multi-qa-mpnet-base-dot-v1
      tokenize: true
      columns:
        text: ds1
    ds2:
      path: sentence-transformers/multi-qa-mpnet-base-dot-v1
      tokenize: true
      columns:
        text: ds2
```

Anything jump out as maybe an issue?
