### ISSUE TITLE
Can't specify embedding model via API?

### ISSUE THREAD

**Issue by scpedicini** [neuml/txtai#632]
I've setup a txtai with the following configuration. 

```yaml
# config.yml
writable: true

embeddings:
  content: true
  defaults: false

  indexes:
    minilm:
      path: "sentence-transformers/all-MiniLM-L6-v2"
    
    nli:
      path: "sentence-transformers/nli-mpnet-base-v2"
```

I'm trying to get the vec embeddings of a given document using the API but cannot figure out how to specify the desired model, e.g.

```bash
curl -X GET "http://localhost:8000/transform?text=hello&index=nli"
```
