### ISSUE TITLE
postgresql + pgvector configrution

### ISSUE THREAD

**Issue by benqethan** [neuml/txtai#917]
I tried to make txtai to load Application(yml_config), but seems the loaddata doesn't happen even i have the vector in the postgresql.
Below is the the yaml file
```
# Embeddings index
embeddings:
  # model: thenlper/gte-base
  ann:
    backend: pgvector
  database:
    backend: postgres
  pgvector:
    url: postgresql://pguser:pgpassword@localhost:5432/pgvector_db
    schema: txtai
  content: postgresql://pguser:pgpassword@localhost:5432/pgvector_db

writable: True
```

Seems it is related to this line in Application class:
```
if loaddata and Embeddings().exists(self.config.get("path"), self.config.get("cloud")):
```

Not sure how to make it work. Please help out. Thanks

**Comment by davidmezzetti** [comment]
txtai doesn't currently have a Postgres backend for index configuration. 

```yaml
path: local path that exists

# Embeddings index
embeddings:
  # model: thenlper/gte-base
  ann:
    backend: pgvector
  database:
    backend: postgres
  pgvector:
    url: postgresql://pguser:pgpassword@localhost:5432/pgvector_db
    schema: txtai
  content: postgresql://pguser:pgpassword@localhost:5432/pgvector_db

writable: True
```

How did you create the data in Postgres?
